--------------------------------------------------------------------------------
-- |
-- Module      :  Graphics.GL.Functions
-- Copyright   :  (c) Sven Panne 2016
-- License     :  BSD3
--
-- Maintainer  :  Sven Panne <svenpanne@gmail.com>
-- Stability   :  stable
-- Portability :  portable
--
-- All raw functions from the
-- <http://www.opengl.org/registry/ OpenGL registry>.
--
--------------------------------------------------------------------------------

module Graphics.GL.Functions (
  module Graphics.GL.Functions.F01,
  module Graphics.GL.Functions.F02,
  module Graphics.GL.Functions.F03,
  module Graphics.GL.Functions.F04,
  module Graphics.GL.Functions.F05,
  module Graphics.GL.Functions.F06,
  module Graphics.GL.Functions.F07,
  module Graphics.GL.Functions.F08,
  module Graphics.GL.Functions.F09,
  module Graphics.GL.Functions.F10,
  module Graphics.GL.Functions.F11,
  module Graphics.GL.Functions.F12,
  module Graphics.GL.Functions.F13,
  module Graphics.GL.Functions.F14,
  module Graphics.GL.Functions.F15,
  module Graphics.GL.Functions.F16,
  module Graphics.GL.Functions.F17,
  module Graphics.GL.Functions.F18,
  module Graphics.GL.Functions.F19,
  module Graphics.GL.Functions.F20,
  module Graphics.GL.Functions.F21,
  module Graphics.GL.Functions.F22,
  module Graphics.GL.Functions.F23,
  module Graphics.GL.Functions.F24,
  module Graphics.GL.Functions.F25,
  module Graphics.GL.Functions.F26,
  module Graphics.GL.Functions.F27,
  module Graphics.GL.Functions.F28,
  module Graphics.GL.Functions.F29,
  module Graphics.GL.Functions.F30,
  module Graphics.GL.Functions.F31,
  module Graphics.GL.Functions.F32,
  module Graphics.GL.Functions.F33,
  module Graphics.GL.Functions.F34,
  module Graphics.GL.Functions.F35,
  module Graphics.GL.Functions.F36,
  module Graphics.GL.Functions.F37,
  module Graphics.GL.Functions.F38,
  module Graphics.GL.Functions.F39,
  module Graphics.GL.Functions.F40,
  module Graphics.GL.Functions.F41,
  module Graphics.GL.Functions.F42,
  module Graphics.GL.Functions.F43,
  module Graphics.GL.Functions.F44,
  module Graphics.GL.Functions.F45,
  module Graphics.GL.Functions.F46,
  module Graphics.GL.Functions.F47,
  module Graphics.GL.Functions.F48,
  module Graphics.GL.Functions.F49,
  module Graphics.GL.Functions.F50,
  module Graphics.GL.Functions.F51,
  module Graphics.GL.Functions.F52,
  module Graphics.GL.Functions.F53,
  module Graphics.GL.Functions.F54,
  module Graphics.GL.Functions.F55,
  module Graphics.GL.Functions.F56,
  module Graphics.GL.Functions.F57,
  module Graphics.GL.Functions.F58,
  module Graphics.GL.Functions.F59,
  module Graphics.GL.Functions.F60,
  module Graphics.GL.Functions.F61,
  module Graphics.GL.Functions.F62,
  module Graphics.GL.Functions.F63,
  module Graphics.GL.Functions.F64,
  module Graphics.GL.Functions.F65,
  module Graphics.GL.Functions.F66,
  module Graphics.GL.Functions.F67,
  module Graphics.GL.Functions.F68,
  module Graphics.GL.Functions.F69,
  module Graphics.GL.Functions.F70,
  module Graphics.GL.Functions.F71,
  module Graphics.GL.Functions.F72,
  module Graphics.GL.Functions.F73,
  module Graphics.GL.Functions.F74,
  module Graphics.GL.Functions.F75,
  module Graphics.GL.Functions.F76,
  module Graphics.GL.Functions.F77,
  module Graphics.GL.Functions.F78,
  module Graphics.GL.Functions.F79
) where

import Graphics.GL.Functions.F01
import Graphics.GL.Functions.F02
import Graphics.GL.Functions.F03
import Graphics.GL.Functions.F04
import Graphics.GL.Functions.F05
import Graphics.GL.Functions.F06
import Graphics.GL.Functions.F07
import Graphics.GL.Functions.F08
import Graphics.GL.Functions.F09
import Graphics.GL.Functions.F10
import Graphics.GL.Functions.F11
import Graphics.GL.Functions.F12
import Graphics.GL.Functions.F13
import Graphics.GL.Functions.F14
import Graphics.GL.Functions.F15
import Graphics.GL.Functions.F16
import Graphics.GL.Functions.F17
import Graphics.GL.Functions.F18
import Graphics.GL.Functions.F19
import Graphics.GL.Functions.F20
import Graphics.GL.Functions.F21
import Graphics.GL.Functions.F22
import Graphics.GL.Functions.F23
import Graphics.GL.Functions.F24
import Graphics.GL.Functions.F25
import Graphics.GL.Functions.F26
import Graphics.GL.Functions.F27
import Graphics.GL.Functions.F28
import Graphics.GL.Functions.F29
import Graphics.GL.Functions.F30
import Graphics.GL.Functions.F31
import Graphics.GL.Functions.F32
import Graphics.GL.Functions.F33
import Graphics.GL.Functions.F34
import Graphics.GL.Functions.F35
import Graphics.GL.Functions.F36
import Graphics.GL.Functions.F37
import Graphics.GL.Functions.F38
import Graphics.GL.Functions.F39
import Graphics.GL.Functions.F40
import Graphics.GL.Functions.F41
import Graphics.GL.Functions.F42
import Graphics.GL.Functions.F43
import Graphics.GL.Functions.F44
import Graphics.GL.Functions.F45
import Graphics.GL.Functions.F46
import Graphics.GL.Functions.F47
import Graphics.GL.Functions.F48
import Graphics.GL.Functions.F49
import Graphics.GL.Functions.F50
import Graphics.GL.Functions.F51
import Graphics.GL.Functions.F52
import Graphics.GL.Functions.F53
import Graphics.GL.Functions.F54
import Graphics.GL.Functions.F55
import Graphics.GL.Functions.F56
import Graphics.GL.Functions.F57
import Graphics.GL.Functions.F58
import Graphics.GL.Functions.F59
import Graphics.GL.Functions.F60
import Graphics.GL.Functions.F61
import Graphics.GL.Functions.F62
import Graphics.GL.Functions.F63
import Graphics.GL.Functions.F64
import Graphics.GL.Functions.F65
import Graphics.GL.Functions.F66
import Graphics.GL.Functions.F67
import Graphics.GL.Functions.F68
import Graphics.GL.Functions.F69
import Graphics.GL.Functions.F70
import Graphics.GL.Functions.F71
import Graphics.GL.Functions.F72
import Graphics.GL.Functions.F73
import Graphics.GL.Functions.F74
import Graphics.GL.Functions.F75
import Graphics.GL.Functions.F76
import Graphics.GL.Functions.F77
import Graphics.GL.Functions.F78
import Graphics.GL.Functions.F79
